latinos/LatinoAnalysis

- Gardener/python/Gardener_cfg.py
- Gardener/python/gardening.py
- Gardener/scripts/mkGardener.py
- ShapeAnalysis/python/ShapeFactory.py
This pull request hopefully integrates the possibility of using friend trees for systematics.
Changes are:
- all gardener modules can output only the modified branches
- all gardener modules can use as input a friend tree for the unmodified branches
- the pruner module outputs a TEventList of the selected events
- mkShapes can handle friend trees (new option unskimmedFriendTreeDir) (example missing)
- full chain implemented in mkGardener.py steps FJESdo, FJESup and FwwSel (to be extended to other steps if needed)
- original behavior preserved
> Handling of systematics with friend trees

- ShapeAnalysis/python/PlotFactory.py
- ShapeAnalysis/python/ShapeFactoryMulti.py
- ShapeAnalysis/scripts/mkDatacards.py
- ShapeAnalysis/scripts/mkPlot.py
- ShapeAnalysis/scripts/mkShapesMulti.py
- Tools/python/batchTools.py
- Tools/scripts/haddfast
For differential analysis we end up with millions of histograms, and the existing factories weren't scaling. The updates here are transparent and won't change the outcome of standard usage, but adds a few new features:
- mkDatacards and mkPlots can use an input directory as an --inputFile argument. The directory must contain one histogram ROOT file per sample. This eliminates the need to run hadd over the sample-split shape files (which is a pure copy operation because no histogram is merged across samples)
- Samples can be split by number of events within a file. With AsMuchAsPossible as the splitting option, for samples with FilesPerJob = 1 and EventsPerJob != 0, multiple jobs are created for each file, processing parts of the file. This may not be useful in the end though; I added the …
> Changes to facilitate larger scale operations

- NanoGardener/python/framework/samples/samplesCrossSections2016.py
Hi. I add some xsec values for 2016 samples (requested by @xjanssen )
- ext samples' values are added simply using the same value of original one
- Correct sample alias in xsec file : WZ_ext1 -> WZ_ext
-Others can be found from reference
-*Need* discussion:
1)TT_TuneCUETP8M2T4,
-> I need further understanding. But It seems like just a tuning variation. I set the xsec to central tuning's value - 831.76 temporarily. Does it make sense?
2)WJetsToLNu_HT70_100
ref	E	(https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns)
doesn't give xsec value for this HT bin. But other bins have their value with kfactor.
Fortunately, HT70_100 has LO xsec  in its McM. Please find 'Generator Parameters' in
https://cms-pdmv.cern.ch/mcm/edit?db_name=requests&prepid=SUS-RunIISummer15wmLHEGS-00103&page=0
.
I …
> Add xsec 2016

- NanoGardener/python/framework/samples/fall17_102X_nAODv4.py
- NanoGardener/python/framework/samples/samplesCrossSections2017.py
---in sample list---
GluGluHToTauTau_M125_ext1
ZZTo4L_ext1
GJets_HT40To100_ext1
TTWjets_ext1
TTZjets_ext1
WJetsToLNu-LO_ext1
DYJetsToLL_M-10to50-LO_ext1
DYJetsToLL_M-50-LO_ext1
DYJetsToLL_M-4to50_HT-100to200_ext1
DYJetsToLL_M-4to50_HT-200to400_ext1
DYJetsToLL_M-4to50_HT-400to600_ext1
DYJetsToLL_M-4to50_HT-600toInf_ext1
DYJetsToLL_M-50_HT-200to400_ext1
DYJetsToLL_M-50_HT-400to600_ext1
---in sample xsec---
GJets_HT40To100_ext1
DYJetsToLL_M-10to50-LO_ext1
DYJetsToLL_M-50-LO_ext1
DYJetsToLL_M-4to50_HT-100to200_ext1
DYJetsToLL_M-4to50_HT-200to400_ext1
DYJetsToLL_M-4to50_HT-400to600_ext1
DYJetsToLL_M-4to50_HT-600toInf_ext1
TTJetsDiLep-LO_ext1
[Question] some of the ext samples don't have their xsec in the xsec python. Should it be added?
GluGluHToTauTau_M125_ext1
ZZTo4L_ext1
TTWjets_ext1 …
> -ext -> _ext for consistent naming

- NanoGardener/python/framework/samples/fall17_nAOD_v1.py
- NanoGardener/python/framework/samples/samplesCrossSections2017.py
@xjanssen . Could you review this PR?
I correct the name of QCD_10to30 sample and add xsec of each QCD samples you requested
> Update 2017 QCD xsec and correct type QCD_10to30 -> QCD_15to30

- NanoGardener/python/framework/PostProcMaker.py
- On a CC7 machine, subprocess gfal-ls cannot be used because of some python library incompatibilities. On the other hand, at least lxplus environment has gfal2 python binding available with the system python, so we can use it instead.
- When reading a non-local NANOAOD, it's faster to first copy the entire file locally with xrdcp than read it through AAA on the fly.
> using gfal2 python bindings in CC7

- NanoGardener/python/data/FatJetMaker_cfg.py
- NanoGardener/python/framework/Steps_cfg.py
- NanoGardener/python/modules/FatJetMaker.py
Hi!
I created a module to clean FatJet collection 
1) kinematics cuts:  minpt, maxeta, max_tau21, mass_range
2) for each FatJet passing the cuts the overlapping with leptons is checked
with a configurable radius, (default 1.0)
3) The CleanJet collection is checked to save a vector with the ids of the jets
not overlapping with the CleanFatJet. (default radius 0.8)
The output of this module is a CleanFatJet collection with pt,eta,phi. Also a jetIdx reference to FatJet original collection is saved.
The list of CleanJet ids not overlapping with FatJets is saved in  CleanJetNotFat_jetIdx collection and relative size nCleanJetNotFat.
> Added cleaning step for FatJets

- NanoGardener/python/framework/Steps_cfg.py
- NanoGardener/python/modules/FatJetMaker.py
Hi. I add jetid cut. 
I set the default jetid to 0. So, there's no impact from this PR if you run the module with default inputs. It cuts fatjet with jetid < input.
The jetid bit definition is like below :
#
bit1 : loose id / bit2 : tight id / bit3 : tightLepVeto
#
@valsdav Do you agree on this? I tested it and saw it works well.
Please note that I set the default =0, there's no difference on output tree.
> Add jetid to fat jet maker

- ShapeAnalysis/python/ShapeFactoryMulti.py
ShapeFactoryMulti would crash if there is a variable to be folded - why was this not caught until now? Anyway this is the bugfix.
> ShapeFactoryMulti bugfix

- ShapeAnalysis/python/PlotFactory.py
- ShapeAnalysis/python/utils.py
- ShapeAnalysis/scripts/mkDatacards.py
- ShapeAnalysis/scripts/mkPlot.py
`subsamples` and `categories` features make mkShapes more efficient but cause trouble downstream (mkPlot and mkDatacard). Here's a way to automatically deal with them (just flattens out all subsamples into new samples and categories into new cuts). There is a bit of nontrivial choice that has been made:
- If a nuisance specifies just the full sample, the sample entry is replaced with all subsamples
- If a nuisance specifies subsample names, those entries are not touched and unspecified subsamples are not inserted
plot.py and structure.py should be written assuming fully flattened samples / cuts.
> deal with subsamples and categories

- NanoGardener/python/data/MCGenOnly_outputbranches.txt
- NanoGardener/python/framework/PostProcMaker.py
- NanoGardener/python/framework/Steps_cfg.py
- NanoGardener/python/modules/RunAssigner.py
Adding a gen-only standalone step for making very light-weight trees for gen-level studies.
This PR will conflict with #55 in the sense that I fixed (what I think is) a bug in PostProcMaker where branchsel was not quoted, but in #55 Pedro decided to add the quotes in the Steps config. So once both are merged, (I think) we should remove the quotes from the DropBranches step.
By the way the use of `os.getenv('CMSSW_BASE')` in the MCGenOnly step in this PR is one way to achieve portability requested in https://github.com/latinos/LatinoAnalysis/pull/55#issuecomment-525699917
There is another module `RunAssigner` - this is just an extraction of the `run_period` assignment of TrigMaker. I ended up not using it, but it might come in handy later; `run_period` is used by other modules but we don't …
> Add genonly config

- NanoGardener/scripts/mkPostProc.py
I found that certain libraries need to be imported here for macros based on MELA to be compiled properly (like https://github.com/latinos/LatinoAnalysis/blob/master/Gardener/python/variables/melaReweighterWW.C).
After this PR we'll be able to use newer versions of the MELA packages (https://github.com/latinos/setup/blob/13TeV/SetupShapeOnly.sh#L117-L120).
> Import libraries to properly compile MELA macros

- ShapeAnalysis/python/PlotFactory.py
In the previous version, if you triggered "plotNormalizedDistributions" then the Fill Style of the plots would become "0" (meaning transparent). This has an effect on the legend (that is created after), and will show the samples with no filled box.
In the new verison, the normalized plot is put as last plot to be prepared, thus removing this issue.
Tested and no issues found (so far)
> Fix mkplot for normalized plots style

- NanoGardener/python/data/FatJetMaker_cfg.py
- NanoGardener/python/framework/Steps_cfg.py
- NanoGardener/python/modules/FatJetMaker.py
- NanoGardener/python/modules/FatJetMassScaler.py
Added module to scale and smear the FatJet mass according to https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetWtagging#2017_scale_factors_and_correctio. 
The module can also be used to compute variations.
Scale factors for the High Purity (HP) category have been added in the cfg file NanoGardener/python/data/FatJetMaker_cfg.py
> Added FatJet Mass scale and smear with variations

- NanoGardener/python/framework/Steps_cfg.py
- NanoGardener/python/modules/qq2vvEWKcorrectionsWeightProducer.py
- NanoGardener/test/postproc.py
- Tools/python/batchTools.py
VV ewk corrections ported to nanoaod from gardener.
- LHE information is used
- apply different corrections if WZ, WW, or ZZ
- it has an effect mainly in the high energy regime, see plot here:
Decision where to plug this in in the post-processing workflow "mkPostProc.py" has to be taken.
The fix in "batchTools.py" is to allow people without a grid proxy to use the plotting tool.
The code in "postproc.py" is to resurrect the testing code for local tests of new modules (and future tutorial)
> vv ewk corrections and more

- ShapeAnalysis/python/PlotFactory.py
This PR adds two small but useful features to mkPlot. 
1) Per variable and cut range data blinding:
Add the option 
```
'blind': {
'cut1': (100, 1000),
'cut2':  'full'
}
```
to the variables dictionary and the data will be blinded according to the specified range on the x-axis. 
2) Now it's possible to setup plot colors from (R,G,B) tuple or hex string in plot.py. Moreover, a 'fill' option has been added in plot.py (default 3001).
> Per variable (and cut) range blinding, colors from rgb or hex string

- NanoGardener/python/modules/HMlnjjVars.py
The first commit fixes indentation problems I had in my editor (though it looked fine on github for some reason).
The second commit are the actual changes:
https://github.com/sebsiebert/LatinoAnalysis/commit/9d532b6cec0c5b7ca79c6f73288521efb74bdb3f?diff=unified
Removed the two lines requested by Pedro on Mattermost for monoH.
The module now only chooses between resolved and boosted category but doesn't split them further into SR / SB / topCR.
_Reverted_ ~Before, the top tagging of the event was done twice, once for boosted and once for resolved. Removed the second one, since the event should be considered tagged in any case (should loop be over CleanJetNotFat or all CleanJet?).
https://github.com/sebsiebert/LatinoAnalysis/blob/9d532b6cec0c5b7ca79c6f73288521efb74bdb3f/NanoGardener/python/mo …
> Removed signal / control region definition from HMlnjjVars module

- NanoGardener/python/modules/HMlnjjVars.py
Other variables were only storing associated jet mjj if the event got tagged as VBF.
This new variable always stores the highest possible mjj of non-W candidate jets as long as the event is containing a fat or resolved hardonic W candidate.
If there is no hadronic W candidate or no 2 additional jets, largest_nonW_mjj equal -999.
> store largest value of mjj from two jets that are not W candidates

- ShapeAnalysis/python/ShapeFactoryMulti.py
- ShapeAnalysis/scripts/mkShapesMulti.py
@DennRoy pointed out that the current implementation of envelope and rms are wrong when jobs are split. Essentially the problem is that
`sum(max(variations)) != max(sum(variations))`
and
`sum(rms(variations)) != rms(sum(variations))`
where sum is the hadd step. What we want is the right hand side but currently we compute the left hand side, i.e., take the envelope and rms per job.
To compute the right hand side properly, I think there is no other way than to place some postprocessing code in the hadd step. So now people are required to do histogram merging through mkShapesMulti.py (which should be the case for most people).
> IMPORTANT FIX for envelope and rms type nuisances

- NanoGardener/python/framework/PostProcMaker.py
- NanoGardener/python/framework/Steps_cfg.py
- NanoGardener/python/framework/samples/fall17_102X_nAODv4.py
- NanoGardener/python/framework/samples/samplesCrossSections2017.py
Simplification of HMlnjjLepSel:
flavour dependant pt cut => Lepton_pt[0] > 30, 
+ l1tightOR2017v5 that didn't come through
2HDMa semilep samples
> HMlnjjVars selection and 2HDMa semilep samples

- ShapeAnalysis/python/ShapeFactoryMulti.py
Made sure all methods work consistently with TH2. Now users can add `'unroll': False` to variables they don't want to unroll to TH1.
The resulting ROOT file will obviously have problems with mkPlot.py. Downstream support is for some other day..
> TH2 support

- NanoGardener/python/data/TrigMaker_cfg.py
- NanoGardener/python/modules/TrigMaker.py
A 5% systematic on Single Electron legs was applied in TrigMaker module to cover lepton WP uncertainties but  it is no more necessary in the last productions that are using multiple WPs.
> Removed 5% electron trigger efficiency old systematic

- NanoGardener/python/modules/FatJetMassScaler.py
If JER centralSF==1, the line
sigma_MC_relative = (current_smear -1)  / ( sqrt(res_SF_central**2 -1))
has zero denominator.(centralSF==1 case will not have additional smearing)
For that case, 'sigma_MC_relative' is fixed to be smeared  to
1+(sigma_MC/mass)*Gaus(0,res_MC)*sqrt(res_SF_var**2-1)
(Same form with central case)
> add JER centralSF==1 case

- NanoGardener/python/framework/PostProcMaker.py
- Tools/python/commonTools.py
In some nanoAODv6 samples branches in the Runs TTree have a trailing "_" in their names. 
This should make the code generic.
> Check branch name in Runs Tree

- ShapeAnalysis/python/PlotFactory.py
All integrals appearing in the legend now are set to show the "visible range only", namely only the bins that are visible in the plots.
This is consistent with mkdatacards too.
> fix integral for legend

- Gardener/python/variables/melaHiggsEFT.C
- NanoGardener/python/framework/Steps_cfg.py
- NanoGardener/python/modules/EFTReweighter.py
- NanoGardener/python/modules/JJH_EFTVars.py
There are two new modules. 
JJH_EFTVars.py calculates the EFT/AC related matrix elements for events with a H->WW->2l2nu candidate and 2 additional jets. Right now only the VBF matrix elements are added, but it is trivial to also include VH if required, this may be useful for Ashish if he decides to study this channel. 
These matrix elements can then be used to form kinematic discriminantes.  
EFTReweighter.py calculates the EFT/AC related matrix elements at generator level. It recognizes both the VBF and GluGlu EFT/AC signal samples and adds the relevant matrix elements to the ntuples. These can then be used to reweight the signal samples. 
Both modules make use of a macro melaHiggsEFT.C which returns a vector of relevant matrix elements. 
Also I added the step VBFl2EFT to Steps_cfg.py, …
> Modules to add MELA EFT variables and gen information to ntuples

- NanoGardener/python/framework/PostProcMaker.py
- NanoGardener/python/framework/Steps_cfg.py
This should fix the UEPS step when the number of files corresponding to the variations is greater than the number of nominal files. 
With this approach we end up with the same number of nominal and varied files.
> Fix UEPS step when nin>nnom

- NanoGardener/python/modules/EFTReweighter.py
The gen level info in the 2017/18 signal samples is quite messy with respect to 2016, a number of additions required.
Now using a function which loops over the mothers of a particle to check if it comes from a Higgs, in  2016 it was always the grandmother, not so for 2017/18.
Now checking for events where W -> gamma W -> e+ e- W and correcting final state particle collections (not present in 2016).
Now checking for events with an additional hadron (rare!) and correcting final state particle collections (not present in 2016).
> Additions to EFTReweighter to run on 2017/18 MC safetly

- ShapeAnalysis/python/PlotFactory.py
- ShapeAnalysis/scripts/mkDatacards.py
- ShapeAnalysis/scripts/mkPlot.py
mkplot normalized stack : produce stack normalized plots for sig v bkg
- use case: you want to compare the shape of the full big vs full signal, but yet you want also to see the contributions from the backgrounds/signal, looking at their different composition. E.g. if a background has a super small contribution, you don't care too much
- how to use: "--plotNormalizedDistributionsTHstack" in mkPlot.py
statistical uncertainty in mkdatacards
- use case: if you want to remove some statistical uncertainty from the histogram, that will be later used by combine for the autoMCstat (a.k.a. bin by bin uncertainty). Possible use case is related to the combine model to be used later (EFT fits re-using the same samples)
- how to use: " 'removeStatUnc' : 1 " should be a field in the file "structure.py" …
> mkplot normalized stack and removal of statistical uncertainty in mkdatacards

- NanoGardener/python/framework/BranchMapping.py
Probably we were never trying to overwrite a variable and this didn't show up, but I think there was a typo. 
Please cross-check before merging!
Davide
> Fixed BranchMapping  fillbranch overwrite check 

- NanoGardener/python/modules/GGHUncertaintyProducer.py
Wrong ordering of the ggH uncertainty now fixed
> fix ggh uncertainty in nanogardener

- NanoGardener/python/modules/JERMaker.py
- NanoGardener/python/modules/PtCorrApplier.py
- NanoGardener/python/modules/rochester_corrections.py
Fix logic in ordering:
before
order=[]
for idx1, pt1 in enumerate(newpt_vec):
pt_idx = 0
for idx2, pt2 in enumerate(newpt_vec):
if pt1 < pt2 or (pt1 == pt2 and idx1 > idx2): pt_idx += 1
order.append(pt_idx)
Now
#
#
order = sorted(range(len(newpt_vec)), key=newpt_vec.__getitem__, reverse=True)
> Fix ordering logic

- ShapeAnalysis/python/PlotFactory.py
- ShapeAnalysis/scripts/mkPlot.py
- ShapeAnalysis/scripts/mkPostFitCombinedPlot.py
Implementation in latinos framework (to be automatic) of the recipe to digest the output of
PostFitShapesFromWorkspace
as explained in
https://hypernews.cern.ch/HyperNews/CMS/get/higgs-combination/1493.html
Still missing: prepare a new "cuts.py" and "variables.py" automatically.
@dittmer 
How to run:
mkPostFitCombinedPlot.py --inputFilePostFitShapesFromWorkspace output_SR2j.root
Complete example: 
mkPostFitCombinedPlot.py   \
--inputFilePostFitShapesFromWorkspace  output_SR2j.root   \
--outputFile  mytest.root  \
--kind   P  \
--cutName  combinedMy  \
--variable mll   \
--structureFile Full2016_v6/structure.py   \
--plotFile Full2016_v6/plot.py \
--lumiText  '36 + 42 /fb'
Including the mkPlot step:
mkPlot.py --pycfg=configuration_combined.py --inputFile mytest.root   --onlyPlot=cratio …
> Postfit plot combined

- NanoGardener/python/modules/EFTReweighter.py
1) There seems to have been a change in nanoAODv7 with respect to the bookkeeping for LHE partons. For the VBF signals we were not picking up the correct number of LHE partons (selecting 4 instead of 2), simple solution is to include pt>0 cut when selecting partons.
2) Previously when testing the H0L1f05 2016 file I had included an event selection requiring DF leptons, so I didn't test all events in the file. Checking again I see about .01% of events where for one of the L-Nu pairs the pdgIds do not match. This seems to be a corruption of the gen level info as its only present for this one file. I have now added a L-Nu pdgId match check for each L-Nu pair in an event, this is ran for the H0L1f05 sample only.
> Fix for VBF AC signals and for H0L1f05 2016 file

- ShapeAnalysis/python/PlotFactory.py
- ShapeAnalysis/scripts/mkPlot.py
Updating y axis label formatting to match official CMS prescription (https://twiki.cern.ch/twiki/bin/viewauth/CMS/Internal/PubGuidelines#Figures_and_tables). Specifically, labels now use the following format:
-- Fixed bin width: "Events / <bin size> <units>", e.g. "Events / 50 MeV" or "Events / 0.1 units"
-- Variable bin width: "Events / bin"
-- Variable bin width, dividing by bin width: "< Events / <unit> >", e.g. "< Events / GeV >"
Units taken from the x axis caption, assuming (unit) or [unit] notation. Default label may be overwritten using the 'yaxis' field in variables.py.
Also added --extraLegend option to place a label in the upper right corner of the plot -- can be used to indicate channel or other information. Optional and does not affect normal running.
> Updating y axis label format in PlotFactory

- ShapeAnalysis/scripts/mkPostFitCombinedPlot.py
- ShapeAnalysis/scripts/mkPostFitControlPlots.py
Post fit control plots (namely for variables NOT used in the fit) need special care for MC stat nuisances, since they do not appear.
With this script they are added into the histogram.
Slides with explanations will follow.
There is also the possibility to perform this in one go with the options:
nonFitVariable --> set to true
and
listOfFilesOriginal
in mkPostFitCombinedPlot.py
Link to slides: https://indico.cern.ch/event/996684/contributions/4248353/attachments/2196635/3714140/Feb-25_Latino_mkPostFitCombinedAdditionalPlot_Massironi.pdf
> Post fit control plots

- ShapeAnalysis/python/PlotFactory.py
Small tweak to the 'blind' feature in PlotFactory. You can now additionally pass it a set of bin indexes such as:
variables['test'] = { ...
'blind' = { category : (1, 2, 6, 7, 8) }
}
to blind the corresponding bins. This may be useful for example in case one wants to blind a given range in an X variable of a 2D unrolled plot of (X, Y)
> Added possibility to blind non-contiguous sets of bins

- ShapeAnalysis/scripts/mkDatacards.py
mkDatacards.py has been updated in order to have the possibility to scale processes by a scale factor. One can now simply scale a given sample - and all related shape nuisances - by adding the 'scaleSample' key in the corresponding sample dictionary defined in structure.py. The value is the scale factor itself.
> Scale sample

- ShapeAnalysis/python/PlotFactory.py
- ShapeAnalysis/scripts/mkPlot.py
While running mkplot.py the files on eos with the trees could have been already removed.
The "_samples_noload" option was already in some samples.py configuration, but it was not showing in mkplot.py (maybe some private code?)
Now it is part of mkplot.py, so that mkplot.py does not require the presence of trees to make the plots.
In samples.py you should have something like this, if you want to exploit this feature:
```
def nanoGetSampleFiles(inputDir, sample):
try:
if _samples_noload:
return []
except NameError:
pass
return getSampleFiles(inputDir, sample, True, 'nanoLatino_')
```
The other modification in this PR is the option to remove of "All MC" in the legend (for some papers we may want to remove ...)
To do so run mkplot.py with the option:
```
--RemoveAllMC
```
> Protection for missing files and removal of all mc in legend

- ShapeAnalysis/python/PlotFactory.py
Add the possibility to have different line styles in normalized plots.
Requested during the review on SMP-20-013.
Options should be in groupPlot
`
groupPlot['VVV']  = {  
'nameHR' : 'VVV',
'isSignal' : 0,
'color': 857, # kAzure -3  
'samples'  : ['VVV']
'line'   :    3    
}
`
Standard line styles:
https://root.cern.ch/doc/master/classTAttLine.html#ATTLINE3
@valsdav to test
> Possibilty to have different line styles in normalized plots

- ShapeAnalysis/scripts/mkDatacards.py
Adding the `perRecoBin: True` key in the nuisance dictionary will decorrelate the nuisance in each category.
The nuisance will be added in each datacard with a different name, appending the cut name to the nuisance name.
Here is an example
https://github.com/latinos/PlotsConfigurations/blob/42aeca3541d5e12139f572c4720dc5a304c98854/Configurations/ggH/Full2016_v7/HTXS_Stage1p2/nuisances.py#L103-L110
> Add perRecoBin functionality in mkDatacards.py

- ShapeAnalysis/scripts/mkDatacards.py
Noticed that mkDatacards.py can get stuck at cleanup, e.g. when closing input file
Following https://root-forum.cern.ch/t/tfile-close-slow/24179 added line to remove input file from list of files
Cleanup of histograms should be unaffected, since all histograms should be owned by output files -- SetDirectory(self._outFile) is called for all histograms read from input file
> Speed up mkDatacards.py

- NanoGardener/python/data/BranchMapping_cfg.py
- NanoGardener/python/data/UltraJECandJER_cfg.py
- NanoGardener/python/data/keepsysts2.txt
- NanoGardener/python/framework/Steps_cfg.py
- NanoGardener/python/modules/UltraJetUncertaintiesProducer.py
Latinos part of the new all-in-one JEC/JER/MET uncertainties module. Pull request created for better understanding of changes.
Version 1.0:
IMPORTANT: module is using NanoAOD tool `jetmetUncertaintiesLatinos.py` which is not part of the official release (yet). Link to my private fork in the following comments.
> New JEC/JER uncertainties UL module - v1

- ShapeAnalysis/scripts/mkShapesMulti.py
If the target rootFile is already present with the same tag, mkShapesMult.py --doHadd True will abort the hadd operation but still cleanup all the partial rootFiles if --doNotCleanup is not passed. Modded it to check the output from the hadd call and in case the target rootfile is present avoid cleaning up by default.
> Modded mkShapes to avoid accidental cleanups

- NanoGardener/python/data/UltraJECandJER_cfg.py
- NanoGardener/python/framework/Steps_cfg.py
- NanoGardener/python/modules/BoostedWtagSF.py
- NanoGardener/python/modules/JERMaker.py
**JERMaker** primary serves as a tool to apply JER smearing on top of nominal jet pt collection. 
This is an updated version which applies smearing both on **AK4 (CleanJet, SubJet) and AK8 (FatJet) collections**.
In case of AK8 collection, it is also possible to apply Jet mass resolution (JMR) and scale corrections (JMS) on both "mass" and groomed "msoftdrop" mass branches. Please note that for UL samples all JMR,JMS and Puppi corrections are equal to unity (but not JER smearing).
**Optional:** JERMaker can be used to store variation branches for both pt and mass (groomed and non-groomed) for all sources of correction uncertainties (JER, JMR, JMS). It is possible to create correlated variations in 6 bins of jet pt and eta OR create one merged general variation branch. 
Note 1: JER …
> JERMaker for UL AK4/AK8 jet collections and adding MCCorr201Xv9 chain.

- NanoGardener/python/modules/l3KinProducer.py
This adds variables used in Sahithi's AZH UL thesis, which is using the Latinos Framework, but primarily situated in the Extended Higgs Sector group. A chi-squared method for recon. is implemented for the semi-leptonic channel. See: https://indico.cern.ch/event/1154439/contributions/4870649/attachments/2448983/4196684/2022_05_23_Higgs_Extended.pdf
> add variables for AZH analysis

- NanoGardener/python/modules/TrigMaker.py
Tentative fix of the random run period generation.
It was previously crashing if the run period started from a number different than 1, as in the `Full2016v9noHIPM` era.
> Fix the random number run period generation

- ShapeAnalysis/scripts/mkDatacards.py
Adding the flag to mkDatacards.py not to load files when executing samples.py, as currently done in mkPlot.py
> Adding option not to load samples in mkDatacards.py

- NanoGardener/python/framework/samples/Summer20UL16_106x_HIPM_nAODv9.py
- NanoGardener/python/framework/samples/Summer20UL16_106x_noHIPM_nAODv9.py
- NanoGardener/python/framework/samples/Summer20UL17_106x_nAODv9.py
- NanoGardener/python/framework/samples/Summer20UL18_106x_nAODv9.py
I added the signal samples for Zjj (Z->LL) for the UL Summer20 campaign. There are two types of samples, one produced by HIG with MJJ-10, named `EWKZ2Jets_ZToLL_M-50_TuneCP5_withDipoleRecoil_13TeV-madgraph-pythia8`, and one produced by SMP for VBF-Z with MJJ-120, named `EWK_LLJJ_MLL-50_MJJ-120_TuneCP5_13TeV-madgraph-pythia8_dipole`. The former is not available for `2016_HIPM` campaign, while the latter is available for all four UL NanoAODv9 production campaigns.
> Adding Zjj samples

- NanoGardener/python/framework/Steps_cfg.py
- ShapeAnalysis/python/ShapeFactoryMulti.py
The BTV POG recommends applying the btagSF for a given JES variation in place of the nominal btagSF when producing the varied kinematics [1]. Currently, we cannot do this for two reasons:
1) We do not save the btagSFs for the minimal set of JES uncertainties (JESAbsolute, JESAbsolute_<year>, JESBBEC1, etc.) but only the btagSF for the combined JES variation
2) We don't have the functionality in mkShapesMulti.py to apply an event weight for a suffix systematic variation.
This PR should fix both issues. However, it has not been tested.
> Produce and use btagSFs for minimal set of JES uncertainties

- ShapeAnalysis/scripts/mkDatacards.py
Currently, the AsLnN order is opposite that expected by combine [1]. This fixes the order, for cases where Latinos analyses using AsLnN for a common nuisance are combined with those which are not.
[1] https://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/part2/settinguptheanalysis/#a-simple-counting-experiment
> Swap AsLnN order

- ShapeAnalysis/python/ShapeFactoryMulti.py
New type of nuisance, for example pdf uncertainty with hessian
See chapter 6 of https://arxiv.org/abs/1510.03865
Nuisance: squared sum of the differences between "variations" and the nominal.
It is similar to the "rms" type, but this one maintains the possible asymmetries up/down, that are removed from the "rms" method.
To use this:
nuisances['QCDscale_'+sample] = {
'name' : 'QCDscale_'+sample,
'kind' : 'weight_square',
'type' : 'shape',
'samples' : { sample: variations }
}
NB: fix compared to PR https://github.com/latinos/LatinoAnalysis/pull/292
> new type of nuisance, squared sum of variations
