Tools/python/batchTools.py

If
```batchType = 'condor'```
is in userConfig.py, CERN batch submission will use HTCondor. Default behavior is to use bsub. HTCondor@CERN defines funky queue names, so the submission function raises an exception if a bad queue name is used.

Batch tools update for HTCondor@CERN

---

NanoGardener/python/framework/PostProcMaker.py

one more CERN-condor change

---

Tools/python/batchTools.py

New settings for hercules submission, a.k.a. mib (milano-bicocca cluster).
All other settings are left untouched and change is transparent

new settings for hercules submission, a.k.a. mib

---

Gardener/python/Gardener_cfg.py
Gardener/python/data/formulasToAdd_MC.py
Gardener/python/variables/triggerMaker.py
NanoGardener/python/framework/samples/samplesCrossSections2016.py
Tools/python/batchTools.py

Copied logic from 2-lepton calculation keeping only single lepton terms.

Added trigger eff. calculation for only 1 lepton

---

NanoGardener/python/framework/samples/Summer16_102X_nAODv4.py

Add Summer16_102X_nAODv4.py.
I changed
'GluGluHToWWTo2L2NuPowheg_M125'
to
'GluGluHToWWTo2L2Nu_pythia8_M125'
Similar naming is on VBFH but I don't change it yet.
Is it okay? If not, I'll revert it.

add Summer16_102X_nAODv4.py

---

NanoGardener/python/framework/PostProcMaker.py
NanoGardener/python/framework/Sites_cfg.py
Tools/python/batchTools.py

Add some lines to run NanoGardener at KISTI T3 .

KISTI T3 configuration on site cfg, batch tools

---

NanoGardener/python/framework/samples/Autumn18_102X_nAODv4_v16.py
NanoGardener/python/framework/samples/Summer16_102X_nAODv4.py
NanoGardener/python/framework/samples/fall17_102X_nAODv4.py
NanoGardener/python/framework/samples/script/update_samples.py

Hi. I made an update on newly delivered samples.
Thanks to @DennRoy as he already updated high mass samples!
The update sample are
For 2016:
WWTo2L2Nu_CUETUp
GluGluWWTo2L2NuHiggs_MCFM
QCD_Pt-50to80_EMEnriched
QCD_Pt-30toInf_DoubleEMEnriched
GluGluHToWWTo2L2Nu_M125_CUETUp
GluGluHToWWTo2L2Nu_M125_minloHJ_NNLOPS
VBFHToTauTau_M125
VBFHToWWTo2L2Nu_alternative_M125
VBFHToWWTo2L2Nu_M125_CUETDown
For 2017:
GluGluHToWWTo2L2NuPowheg_M125
HZJ_HToWW_M125
For 2018:
tZq_ll
Also, I made a script to help update the sample list py.(I guess some of our users have better one..)
Can I add this script to our repository?
Let me explain how it works
(1)First, set campaign and python file you want to update
(for example)
>campaign='RunIISummer16NanoAODv4'
>inputfile='Summer16_102X_nAODv4.py'
(2)take commented …

Update nanoaodv4 list may10 2019

---

NanoGardener/python/framework/samples/Autumn18_102X_nAODv4.py
NanoGardener/python/framework/samples/Autumn18_102X_nAODv4_v16.py

Removing GJets entries (which are datasets with v16 GT) from Autumn18_102X_nAODv4.py and adding them into _v16.py.

oops wrong file

---

NanoGardener/python/framework/PostProcMaker.py

As discussed over Mattermost with @xjanssen .

Download the input file regardless of iniStep

---

NanoGardener/python/modules/TrigMaker.py

This should fix the >1 efficiencies found by @xjanssen and @SenneVanPutte. Can you guys please check the logic again? Also @lviliani.

trigger efficiency mixtrure of single and duple electron fix

---

NanoGardener/python/modules/DressedLeptonProducer.py

Photon was always being added to the last lepton.

Bugfix for DressedLepton module

---

NanoGardener/python/framework/Steps_cfg.py
NanoGardener/python/modules/FatJetMaker.py
NanoGardener/python/modules/HMlnjjVars.py
NanoGardener/python/modules/HMlnjjVarsGen.py
NanoGardener/python/modules/HMsemiVars.py
NanoGardener/python/modules/WhadJetSel.py
NanoGardener/python/modules/WlepMaker.py

Analysis categories and mass reconstructions are saved as tree, making a new module "HMlnjjVars.py".

High mass semileptonic analysis variable module

---

NanoGardener/python/modules/FatJetMaker.py

Now the module works also if it is run right after the LeptonMaker module in the Step.

Fix FatJetMaker module if run after LeptonMaker

---

NanoGardener/python/framework/samples/fall17_102X_nAODv4.py

Added QCD enriched samples

---

Gardener/python/variables/qq2zzEWKcorrectionsWeight.py
NanoGardener/python/modules/qq2vvEWKcorrectionsWeightProducer.py
NanoGardener/test/postproc.py

Fix of VV ewk. Apparently it's years since this bug is there ... we  just never run this module, or the old one (gardener) from which it was copied.

Fix for ZZ and ewk corrections

---

ShapeAnalysis/python/PlotFactory.py
ShapeAnalysis/scripts/easyDescription.py
ShapeAnalysis/test/draw/DrawNuisancesAll.py

Adaptation of old utilities to new code developments.
Please, do **NOT** merge till mentioned.
This PR is to keep track of the fixes of old code and restoration of features that got lost with time but they can still be useful.
So far:
- mkPlot.py  : allow plot of uncertainty band on MC even if "data" points are missing
- easyDescription.py : add new configuration files that can be unrolled
- DrawNuisancesAll.py  : tool to plot the effect of shape nuisances on observed variables made it work again with new configurations

Adaptation of old utilities to new code developments

---

ShapeAnalysis/python/ShapeFactoryMulti.py

Was using numpy flatiter wrongly

---

NanoGardener/python/modules/qq2vvEWKcorrectionsWeightProducer.py

WZ ewk corrections (addition of WZ>lvqq case)
@valsdav

WZ ewk corrections (addition of WZ>lvqq case)

---

Gardener/python/variables/melaReweighterWW.C
NanoGardener/python/framework/Steps_cfg.py
NanoGardener/python/modules/HMlnjjVarsGen.py

BWEwkSingletReweighter: weightStoB update after discussion with Ulascan
Others are for HMlnjj step inserted with "_Dev": i'll erase this one eventually, for the moment leave it that way please.

weightStoB update after discussion with Ulascan

---

ShapeAnalysis/python/ShapeFactoryMulti.py

New suffix-based and optionally friend-based systematics scheme

Analysis with branchmap

---

ShapeAnalysis/python/PlotFactory.py

mkPlot new feature: scale only overlaid signal and not in the stacked version
See chat on Mattermost.

mkplot new feature: scale only overlaid signal and not in the stacked version

---

ShapeAnalysis/python/PlotFactory.py
ShapeAnalysis/scripts/mkPlot.py

mkplot addition: possibility to plot in the normalized plot for shape comparison also data.
It could be useful to compare data vs MC shape
@mapellidario

mkplot addition: possibility to plot in the normalized plot for shape comparison also data

---

ShapeAnalysis/test/draw/DrawNuisances.cxx

Ratio plot to see the effect on the nuisances on observables
@valsdav

Improved ratio plot for nuisances

---

NanoGardener/python/framework/PostProcMaker.py

Pass sample name to module.
Will use this for MonoHiggs module.

RPLME_SAMPLE

---

NanoGardener/python/modules/qq2VEWKcorrectionsWeightProducer.py

EWK NLO corrections for W sample fixed.
Thanks to @SenneVanPutte to spotting this typo.

Fix ewk corrections for W sample

---

NanoGardener/python/data/BranchMapping_cfg.py
NanoGardener/python/framework/Steps_cfg.py

Steps for the MonoHiggs semi-leptonic analysis included in the DATA/MCCombJJLNu20X steps.
Added missing comma's to the BranchMapping_cfg.py

MHSemiLepVars to CombJJLNu

---

NanoGardener/python/framework/Steps_cfg.py

Fix typo that prevented l3Kin to be run for JES_suffix variation trees

Fix l3kin for JES_suffix variations

---

NanoGardener/python/framework/samples/samplesCrossSections2017.py
NanoGardener/python/framework/samples/samplesCrossSections2018.py

Same ref as Pt binned samples.

fix XS of nJet binned W+jets to semilep

---

Gardener/python/variables/qq2vvEWKcorrectionsWeight.C
NanoGardener/python/framework/Steps_cfg.py
NanoGardener/python/modules/qq2vvEWKcorrectionsWeightProducer.py
NanoGardener/test/README.md
NanoGardener/test/test.py

Thanks to @SenneVanPutte  for spotting this.
Some comments and the origin of these corrections has been added to the code, for future reference.
A fix on the lepton pairing has been added. It was a left-over from Run 1 latino ntuples, where all objects were "pt ordered", while it's not the case here.

WW ewk corrections

---

NanoGardener/python/framework/Steps_cfg.py
NanoGardener/python/modules/MHSemiLepVars.py

Adding steps for MonoHiggs semi-leptonic to the MCCombJJLNu sys chains.
Fixing few bug's in the process

Mono higgs semi lep systematic steps

---

NanoGardener/python/framework/Productions_cfg.py

Change v7 productions to use NanoAODv7 samples

Use NanoAODv7 in v7 production

---

NanoGardener/python/modules/LeptonFakeWMaker.py

Small rework on naming convention.
nLepton == 1 fix

Fake weight 1l uncertainties

---

NanoGardener/python/framework/samples/VBSjjlnu_samples.py

Removed unused W+jets Pt binned samples and corrected names of Data samples

Fixed Data samples name for combined skim

---

NanoGardener/python/modules/qq2vv2lnujjEWKcorrectionsWeightProducer.py

qq2vv2lnujjEWKcor_fix

---

NanoGardener/python/framework/PostProcMaker.py
NanoGardener/python/framework/Steps_cfg.py
NanoGardener/python/framework/samples/Autumn18_102X_nAODv7.py
NanoGardener/python/framework/samples/Summer16_102X_nAODv7.py
NanoGardener/python/framework/samples/VBSjjlnu_samples.py
NanoGardener/python/framework/samples/fall17_102X_nAODv7.py
NanoGardener/python/framework/samples/samplesCrossSections2016.py
Tools/python/batchTools.py

Set `FORCE_GFAL_SHELL=True` in the userConfig.py to avoid gfal lib problems in CMSSW_10_6_4 when PostProcessing files from EOS folders

New VBS signal samples and fixed post-processing from EOS

---

NanoGardener/python/modules/LeptonFakeWMaker.py

There was a missing underscore in the branch name when filling.
Line 555 was a copy paste mistake

typo fixes

---

NanoGardener/python/framework/samples/Autumn18_102X_nAODv7.py
NanoGardener/python/framework/samples/Summer16_102X_nAODv7.py
NanoGardener/python/framework/samples/fall17_102X_nAODv7.py
NanoGardener/python/framework/samples/samplesCrossSections2016.py
NanoGardener/python/framework/samples/samplesCrossSections2017.py
NanoGardener/python/framework/samples/samplesCrossSections2018.py

Add NanoAODv7 datasets and cross sections information for polarized EW WZ samples

add samples for polarized EW WZ

---

NanoGardener/python/framework/Steps_cfg.py

wNLOEWK fix

---

NanoGardener/python/framework/Steps_cfg.py
NanoGardener/python/framework/samples/MonoHjjlnu_samples.py

adding MonoHjjlnu sample setup's

adding MonoHjjlnu sample setup's

---

NanoGardener/python/framework/Steps_cfg.py

Add missing DYMVA, monoH and EFT vars to JER chain.

Add DYMVA,monoH,EFT to JER chain

---

ShapeAnalysis/python/PlotFactory.py
ShapeAnalysis/scripts/mkPlot.py

removal of preliminary in plots

---

ShapeAnalysis/python/PlotFactory.py

Some fixes for the uncertainty bands in ratio and difference plots and in the stacked plots, since some inconsistencies were there.
In particular:
- the uncertainty bar was put on the stacked BKG only, not including signal, also when histo_total was given (reminder: histo_total, as the name says, is total, including also the signal, if not bkg only fit is performed)
- the MC/MC ratio plot had some inconsistencies on uncertainty/MC, with MC including or not the signal. Now at least it should be consistent (and comments are added to the code)
Several description comments have been added, in order to improve maintainability of the code.
@valsdav : for SMP-20-013

Some possible fixes and comments in mkplot

---

ShapeAnalysis/scripts/mkPostFitPlot.py

look for histo's in correct folder

mkPostFitPlot fix

---

Gardener/python/variables/ZWWVar.C
NanoGardener/python/modules/l3KinProducer.py

Fixed bug in l3KinProducer (dangling WH3l_nbjet branch), also fixed issue with ZWWVar.C (tag still listed as input variable in initial setJet declaration).

Bugfix updating lNKin variables

---

NanoGardener/python/modules/LeptonSFMaker.py

Forgot to change the actual loading of the stat / syst SFs from the textfile

Fixing ele SF calculation

---

NanoGardener/python/framework/samples/Summer20UL16_106x_HIPM_nAODv9.py
NanoGardener/python/framework/samples/Summer20UL16_106x_noHIPM_nAODv9.py
NanoGardener/python/framework/samples/Summer20UL17_106x_nAODv9.py
NanoGardener/python/framework/samples/Summer20UL18_106x_nAODv9.py
NanoGardener/python/framework/samples/samplesCrossSections_UL.py

Reverts latinos/LatinoAnalysis#278

Revert "added WW aTGC samples"
